### ISSUE TITLE
Reproducible builds: manpage includes the build date

### ISSUE THREAD

**Issue by geor-g** [jwilk/mwic#8]
Hi Jakub,

Currently, mwic doesn't [build reproducible](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/mwic.html), as the manpage includes the build date. There is a [Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831779) which tracks "making the output of rst2man reproducible".

As long as this isn't solved:

- Is the date needed inside the manpage?
- If so: What about replacing it after building, for example with the date of the last release, taken from the changelog?

Thanks for your work,
cheers,
Georg

**Comment by jwilk** [comment]
Thanks for the bug report.
I've fixed this in b34ec23082995ef7d59fc43eb9b708c25560fb47.
I don't have immediate plans for a new release, so if you're in a hurry, please cherry-pick the patch for Debian.

**Comment by geor-g** [comment]
Thanks a lot for your fast reply, and the patch. I'm not in a hurry, I'll wait for the next release. I've tagged the bug in the Debian BTS accordingly. Feel free to close this one, here.

**Comment by jwilk** [comment]
Fixed in [0.7.7](https://github.com/jwilk/mwic/releases/tag/0.7.7).
